jobs:
  - job:
    displayName: 'Create and Publish Lambda Artifact for Hello World Function'
    steps:
    
    - script: |
        set -e
        set -x

        # Zip hello_world.py file for Lambda
        LAMBDA_DIR='src/lambda/nice_lambda'
        cd $LAMBDA_DIR
        zip -r hello_world.zip hello_world.py
        echo "Listing contents of the directory '$(pwd)'"
        ls
      displayName: 'Build Code Artifact For Hello World Lambda'
    - publish: src/lambda/nice_lambda/hello_world.zip
      artifact: nice_lambda
      displayName: 'Publish Hello World Lambda zip as an Azure Pipeline Artifact named lambda_function'
