jobs:
  - job:
    displayName: 'Create and Publish Python Artifact for Athena View Creation'
    steps:
    - script: |
        set -e
        set -x

        echo "Listing contents of the directory '$(pwd)'"
        ls
      displayName: 'Build Code Artifact For Athena view'

    - publish: src/pyscripts/create_view.py
      artifact: athena_pyscript
      displayName: 'Publish the python script to create athena view as an artifact'
